### ISSUE TITLE
 BadMethodCallException     Method Lenius\LaravelBasket\Console\EcommerceCommand::getAppNamespace does not exist.

### ISSUE THREAD

**Issue by DimTWH** [Lenius/laravel-ecommerce#1]
Hello i wanted to try and install your basket packages but i get this error:

  BadMethodCallException 

  Method Lenius\LaravelBasket\Console\EcommerceCommand::getAppNamespace does not exist.

  at C:\xampp\htdocs\WineAttitude\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕

  • Bad Method Call: Did you mean Lenius\LaravelBasket\Console\EcommerceCommand::getName() ?

  1   C:\xampp\htdocs\WineAttitude\vendor\lenius\laravel-basket\src\Console\EcommerceCommand.php:117
      Illuminate\Console\Command::__call("getAppNamespace", [])

  2   C:\xampp\htdocs\WineAttitude\vendor\lenius\laravel-basket\src\Console\EcommerceCommand.php:81
      Lenius\LaravelBasket\Console\EcommerceCommand::compileControllers()

What can i do to resolve this please?
Thanks

**Comment by cjonstrup** [comment]
Hi

What version are you running?

**Comment by DimTWH** [comment]
Hi
I’m running version 9 of Laravel. Is it compatible
Thanks.

**Comment by cjonstrup** [comment]
Are you sure you are testing https://github.com/Lenius/laravel-ecommerce and not https://github.com/Lenius/laravel-basket?

**Comment by DimTWH** [comment]
Indeed I was using the Laravel-basket repository. But I also did “php artisan make:ecommerce”
Is it the same as Laravel-ecommerce?

**Comment by cjonstrup** [comment]
If you are using https://github.com/Lenius/laravel-ecommerce you can publish the files like

```
php artisan vendor:publish --provider="Lenius\LaravelEcommerce\EcommerceServiceProvider" --tag="config"
php artisan vendor:publish --provider="Lenius\LaravelEcommerce\EcommerceServiceProvider" --tag="lang"
php artisan vendor:publish --provider="Lenius\LaravelEcommerce\EcommerceServiceProvider" --tag="views"
```

You can disable the controller for the demo in

config/ecommerce.php change the 'disable_default_route' => true,

Then make a copy of
https://github.com/Lenius/laravel-ecommerce/blob/main/src/Http/Controllers/EcommerceController.php and place it in your app/Http/Controller. Remember to change the namespace

The https://github.com/Lenius/laravel-ecommerce/blob/main/resources/views/basket.blade.php has a example of the basket.

**Comment by DimTWH** [comment]
Hello
I will try this tomorrow a.s.a.p.
Thanks for the support
I will contact you if something goes wrong.
